apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fashionable-sailfish-go 
  janus-idp.io/tekton: fashionable-sailfish-go
  backstage.io/kubernetes-id: fashionable-sailfish-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fashionable-sailfish-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  